@multiwhats_api_HostAddress = http://localhost:51563

### Registrar Usuário
POST {{multiwhats_api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "nome": "Joao Igor",
  "senha": "123123"
}

### Login
# @name login
POST {{multiwhats_api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "nome": "Joao Igor",
  "senha": "123123"
}

### Logout
POST {{multiwhats_api_HostAddress}}/api/auth/logout
Authorization: Bearer {{login.response.body.token}}

### Criar Contato
# @name criarContato
POST {{multiwhats_api_HostAddress}}/criar
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "nome": "Maria Silva",
  "numero": "5515987654321",
  "grupoId": null,
  "ocorrenciaAtualId": null
}

### Listar todos os Contatos
GET {{multiwhats_api_HostAddress}}/pegar/todos
Authorization: Bearer {{login.response.body.token}}

### Buscar Contato por ID
GET {{multiwhats_api_HostAddress}}/pegar/1
Authorization: Bearer {{login.response.body.token}}

### Enviar Mensagem (ASP.NET -> Node.js -> WhatsApp)
POST {{multiwhats_api_HostAddress}}/api/send
Content-Type: application/json

{
  "numero": "5515996880359",
  "conteudo": "O multi-whats está funcionando!!"
}

### Deletar Contato
DELETE {{multiwhats_api_HostAddress}}/delete/1
Authorization: Bearer {{login.response.body.token}}

### Webhook - Receber Mensagem
POST {{multiwhats_api_HostAddress}}/api/webhook/whatsapp
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "from": "5515987654321",
  "body": "Olá, tudo bem?",
  "timestamp": 1712345678,
  "notifyName": "Maria Silva"
}
