<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>multiwhats_api</RootNamespace>
    <UserSecretsId>e1b6a0d4-1ad8-4fb5-8e03-e1f4ede9842f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src\repostories\**" />
    <Content Remove="src\repostories\**" />
    <EmbeddedResource Remove="src\repostories\**" />
    <None Remove="src\repostories\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Migrations\" />
	  <Folder Include="src\repositories\repositories\" />
	  <Folder Include="src\usecases\interfaces\ChatInterfaces\" />
	</ItemGroup>

</Project>
